name: "Setup node dependencies"
description: "Setup all node dependencies necessary for deployment"

runs:
  using: "composite"
  steps:
    - name: Upgrade NPM to 6.14.8
      run: |
        npm i -g npm@6.14.8
      shell: bash

    - name: "Install dependencies"
      run: |
        npm ci
      shell: bash
