runs:
  using: "composite"
  steps:
    - name: Setup Node.js 14.12.0
      uses: actions/setup-node@v1
      with:
        node-version: "14.12.0"

    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-

    - name: Upgrade NPM to 6.14.8
      run: |
        npm i -g npm@6.14.8

    - name: "Install dependencies"
      run: |
        npm ci
