name: benchmark

# Refer to https://help.github.com/en/articles/workflow-syntax-for-github-actions for documentation on Actions.
# on:
#   release:
#     types:
#       - prereleased
on: push

jobs:
  benchmark:
    runs-on: ubuntu-latest
    # environment:
    #   name: benchmark

    steps:
      - uses: actions/checkout@v2
      # - name: Validate release tag
      #   run: |
      #     # We only want to run on tags looking like refs/tags/v1200.
      #     echo "Checking tag: $GITHUB_REF"
      #     [[ "${GITHUB_REF:10:1}" == "v" ]] || exit 1

      - name: Setup Node.js 14.12.0
        uses: actions/setup-node@v1
        with:
          node-version: "14.12.0"

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      # - name: "Setup node dependencies"
      #   uses: ./.github/actions/setup-node-deps
      # - name: "Build asset"
      #   uses: ./.github/actions/build-asset

      - name: Benchmark
        # if: env.AWS_ACCESS_KEY_ID && env.AWS_SECRET_ACCESS_KEY
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.BENCHMARK_AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.BENCHMARK_AWS_SECRET_ACCESS_KEY }}
        #   AWS_REGION: ${{ secrets.BENCHMARK_AWS_REGION }}
          CI: "true"
        run: |
          export BENCHMARK_SUFFIX=$$RANDOM
          echo $BENCHMARK_SUFFIX
          # npm run benchmark

      # - name: Commit benchmark results
      #   uses: codetalkio/add-and-commit@v6
      #   with:
      #     author_name: GitHub Actions
      #     author_email: no-reply@codetalk.io
      #     message: "Bot: Updating benchmark results"
      #     add: "./benchmark/*"
      #     branch: master
